# Generated by Django 4.0.4 on 2022-05-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
