# Generated by Django 4.0.4 on 2022-05-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
