# Generated by Django 4.0.4 on 2022-05-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_rename_hpassword_user_hashpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=200)),
                ('total', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.user')),
            ],
        ),
    ]
