# Generated by Django 4.0.4 on 2022-05-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='userid',
            new_name='user_id',
        ),
    ]
